# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='运输方式')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='运费')),
            ],
            options={
                'verbose_name': '运输方式管理',
                'verbose_name_plural': '运输方式管理',
            },
        ),
    ]
