# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190123_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pay_name', models.CharField(max_length=20, verbose_name='支付方式')),
            ],
            options={
                'verbose_name': '支付方式',
                'verbose_name_plural': '支付方式',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='配送方式')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='金额')),
            ],
            options={
                'verbose_name': '配送方式',
                'verbose_name_plural': '配送方式',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=100, verbose_name='收货人')),
                ('phone', models.CharField(max_length=11, verbose_name='收货人电话')),
                ('hcity', models.CharField(max_length=100, verbose_name='省')),
                ('hproper', models.CharField(blank=True, default='', max_length=100, verbose_name='省')),
                ('harea', models.CharField(blank=True, default='', max_length=100, verbose_name='省')),
                ('brief', models.CharField(max_length=255, verbose_name='详细地址')),
                ('isDefault', models.BooleanField(default=False, verbose_name='是否设置为默认')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '收货地址管理',
                'verbose_name_plural': '收货地址管理',
            },
        ),
    ]
